services:
  pleroma:
    image: git.pleroma.social:5050/pleroma/pleroma:stable
    container_name: "pleroma"
    hostname: "pleroma"
    labels:
      - "org.label-schema.group=pleroma"
    restart: always
    env_file: ./environments/pleroma/pleroma.env
    depends_on:
      - pleroma-db
    networks:
      - internal_network
      - external_network
    volumes:
      - ./volumes/pleroma/config.exs:/var/lib/pleroma/config.exs
      - ./volumes/pleroma/uploads:/var/lib/pleroma/uploads

  pleroma-db:
    image: postgres:16-alpine
    container_name: "pleroma-db"
    hostname: "pleroma-db"
    labels:
      - "com.centurylinklabs.watchtower.enable=False"
      - "org.label-schema.group=pleroma"
    restart: always
    env_file: ./environments/pleroma-db/postgres.env
    networks:
      - internal_network
    volumes:
      - ./volumes/pleroma-db/pgdata:/var/lib/postgresql/data
      - ./volumes/pleroma-db/pginit:/docker-entrypoint-initdb.d

  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: always
    env_file: ./environments/cloudflared/cloudflared.env
    command: tunnel --no-autoupdate run
    depends_on:
      - pleroma
    networks:
      - external_network
      - internal_network

networks:
  internal_network:
    internal: true
  external_network:
